[features]
seeds = false
skip-lint = false
[programs.localnet]
lottery_contract = "53kjJ9cywtGofrGyQ3hv8XLAhAJRWqdWRTXTNfdAn46d"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/Users/tristan/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
